// gridLayout.js - the DataGridView sizing policy, kept in its own file so it
// can be tested against the Go implementation it mirrors.
//
// This is a deliberate port of DataGridView.computeWidths / layoutRows in
// GoForms (datagridview.go). The visual designer's whole promise is that the
// canvas shows what will really appear at runtime, so the two must agree;
// test/gridLayout.test.js checks them against golden values generated by
// GoForms' own test (TestGoldenGridWidths).
//
// It attaches to `globalThis` rather than using ES modules so the webview can
// load it with a plain <script> under its strict CSP, and Node can require it
// unchanged.
(function (root) {
	'use strict';

	// Fyne metrics the port depends on: theme.Padding() is 4, and one line of
	// text measures ~19 units tall at the default theme text size.
	var PAD = 4;
	var TEXT_H = 19;
	var HEADER_H = TEXT_H + PAD * 4;
	var LINE_H = TEXT_H + PAD * 2;
	var DEFAULT_ROW_H = 30;
	var DEFAULT_COL_W = 100;
	var MIN_COL_W = 40;
	var SCROLLBAR = 16;

	function canScrollH(scrollBars) {
		return scrollBars === 'ScrollBarsHorizontal' || scrollBars === 'ScrollBarsBoth';
	}

	function canScrollV(scrollBars) {
		return scrollBars === 'ScrollBarsVertical' || scrollBars === 'ScrollBarsBoth';
	}

	/**
	 * computeWidths mirrors DataGridView.computeWidths.
	 *
	 * @param opts.cols        column titles
	 * @param opts.rows        cell data, one array per row
	 * @param opts.width       the control's width
	 * @param opts.columnsMode "SizeFixed" | "SizeToContent" | "SizeFill"
	 * @param opts.scrollBars  "ScrollBarsNone" | "...Horizontal" | "...Vertical" | "...Both"
	 * @param opts.measure     (text, bold) => width, so tests can inject exact
	 *                         metrics instead of the browser's
	 */
	function computeWidths(opts) {
		var cols = opts.cols || [];
		var rows = opts.rows || [];
		var mode = opts.columnsMode || 'SizeFixed';
		var scrollBars = opts.scrollBars || 'ScrollBarsBoth';
		var measure = opts.measure;

		var avail = opts.width;
		if (canScrollV(scrollBars)) {
			avail -= SCROLLBAR;
		}

		var widths;
		if (mode === 'SizeToContent') {
			widths = cols.map(function (title, i) {
				var w = measure(title, true) + PAD * 4;
				for (var r = 0; r < rows.length; r++) {
					if (i < rows[r].length) {
						w = Math.max(w, measure(rows[r][i], false) + PAD * 4);
					}
				}
				return Math.max(w, MIN_COL_W);
			});
		} else if (mode === 'SizeFill') {
			// Every column carries the same weight here: per-column FillWeight
			// isn't expressible in the designer's source model, only the
			// grid-wide SetAutoSizeColumnsMode is.
			var slack = Math.max(0, avail - cols.length * MIN_COL_W);
			widths = cols.map(function () {
				return Math.max(MIN_COL_W, MIN_COL_W + slack / cols.length);
			});
		} else {
			widths = cols.map(function () {
				return DEFAULT_COL_W;
			});
		}

		// With horizontal scrolling off, squeeze to fit - never below the
		// per-column minimum. Overflow past the sum of the minimums is simply
		// clipped, which is what the Go side does too.
		if (!canScrollH(scrollBars)) {
			var total = widths.reduce(function (a, b) {
				return a + b;
			}, 0);
			if (total > avail && avail > 0) {
				var shrinkable = widths.reduce(function (a, w) {
					return a + (w - MIN_COL_W);
				}, 0);
				if (shrinkable > 0) {
					var ratio = Math.min(1, (total - avail) / shrinkable);
					widths = widths.map(function (w) {
						return w - (w - MIN_COL_W) * ratio;
					});
				}
			}
		}
		return widths;
	}

	/** rowHeight mirrors DataGridView.measureRowHeight. */
	function rowHeight(row, opts) {
		var fixed = opts.rowHeight || DEFAULT_ROW_H;
		if (opts.rowsMode !== 'SizeToContent') {
			return fixed;
		}
		var lines = row.reduce(function (n, cell) {
			return Math.max(n, String(cell).split('\n').length);
		}, 1);
		return Math.max(fixed, lines * LINE_H + PAD * 2);
	}

	root.GoFormsGridLayout = {
		PAD: PAD,
		TEXT_H: TEXT_H,
		HEADER_H: HEADER_H,
		LINE_H: LINE_H,
		DEFAULT_ROW_H: DEFAULT_ROW_H,
		DEFAULT_COL_W: DEFAULT_COL_W,
		MIN_COL_W: MIN_COL_W,
		SCROLLBAR: SCROLLBAR,
		canScrollH: canScrollH,
		canScrollV: canScrollV,
		computeWidths: computeWidths,
		rowHeight: rowHeight,
	};
})(typeof globalThis !== 'undefined' ? globalThis : this);
